# Site settings
title:       Tw93
email:       tw93@qq.com
author:      tang wei
description: "Love JavaScript,Thanks Node.js."
baseurl:     ""
url:         "http://tw93.github.io/"

# Google analytics
google_analytics: UA-57207999-1

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
show_social_icons: false
stackoverflow_id:
github_username: tw93
zhihu_id: tw93
sina_id: tw1118
bitcoin_url:
paypal_url:
flattr_button:


# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    /:year-:month-:day/:title.html
paginate:     3
sass:
  compressed: true
gems:
  - jekyll-sitemap
